#!.venv/bin/python
import typer

from smapper_toolbox.cli import cam_info_app, kalibr_app, transforms_app
from smapper_toolbox.config import ConfigManager
from smapper_toolbox.logger import logger

app = typer.Typer()
app.add_typer(kalibr_app, name="kalibr")
app.add_typer(transforms_app, name="transforms")
app.add_typer(cam_info_app, name="cam_info")


@app.callback()
def main(ctx: typer.Context):
    """
    A toolbox to help automate the calibration process using dockerised kalibr.

    This tool helps calibrate cameras and IMUs using the Kalibr toolbox in a Docker container.
    It supports camera calibration, IMU calibration, and camera-IMU calibration.
    """
    config_manager = ConfigManager()
    config = config_manager.config

    ctx.obj = {"config": config}


if __name__ == "__main__":
    # typer.run(main)
    logger.info("Hello from calib-toolbox!")
    app()
