"""
Helper functions for calibration file management.

This module provides utility functions to move and organize calibration result files generated by Kalibr.
"""

import os
import shutil
from typing import List

from smapper_toolbox.rosbags.analyzer import RosbagInfo


def move_kalibr_results(bags: List[RosbagInfo], source: str, destination: str) -> None:
    if not os.path.exists(destination):
        os.makedirs(destination)

    for bag in bags:
        filename = bag.name.split(".")[0]
        results_dir = os.path.join(destination, filename)
        os.makedirs(results_dir, exist_ok=True)

        for file in os.listdir(source):
            file_extension = file.split(".")[-1]
            if filename in file and file_extension in ["yaml", "pdf", "txt"]:
                src = os.path.join(source, file)
                dest = os.path.join(results_dir, file)
                shutil.move(src, dest)
