# Global settings
workspace:
    base_dir: ~/work/smapper
    calibration_dir: ~/work/smapper/calibration/kalibr
    rosbags_dir: ~/rosbags

# Docker configuration
docker:
    image_tag: kalibr

# Target configurations (can have multiple)
targets:
    default:
        type: apriltag
        filename: april_6x6_80x80cm.yaml

    checkerboard:
        type: checkerboard
        filename: checkerboard_9x6_0.05m.yaml
        # path: custom_path

# Performance settings
performance:
    parallel_conversions: 4
    parallel_calibrations: 4
    memory_per_job: 2g

# Calibration modes
calibration:
    camera:
        save_dir: static/camera
        target: default # Reference to targets section
        camera_model: pinhole-radtan
        output_formats: [yaml, pdf, txt]
        validation:
            min_images: 50
            max_reprojection_error: 2.0

    imu:
        save_dir: static/imu
        random_walk_multiplier: 10
        white_noise_multiplier: 5
        validation:
            min_duration_hours: 3
            max_bias_drift: 0.01

    camera_imu:
        save_dir: dynamic
        target: default
        reprojection_sigma: 1.0
        output_formats: [yaml, pdf, txt]
        validation:
            min_images: 100
            max_reprojection_error: 1.5
