# Global settings
workspace:
    # Path to smapper repository
    base_dir: ~/Work/smapper/
    # Path where targets are and where to save results
    calibration_dir: ~/Work/smapper/calibration/kalibr
    # Root directory where rosbags are. Should contain a ros2 folder with the bags
    rosbags_dir: /run/media/pedros/smapper_ssd/calibrations/

# Docker configuration
docker:
    image_tag: kalibr
    # dockerfile_path: path_to_dockerfile

# Target configurations (can have multiple)
targets:
    default:
        type: apriltag
        filename: april_6x6_80x80cm.yaml

# Performance settings
performance:
    # Number of parallel ros2 bags to ros1 bags conversions
    parallel_conversions: 4
    # Number of parallel calibration happen at the same time when running Kalibr
    parallel_calibrations: 4

# Calibration modes
calibration:
    camera:
        # Where to save results. [Relative to calibration_dir]
        save_dir: dynamic/intrinsics
        target: default # Reference to targets section
        camera_model: pinhole-radtan
        # The following settings do NOT change.
        output_formats: [yaml, pdf, txt]
        validation:
            min_images: 50
            max_reprojection_error: 2.0

    imu:
        # Where to save results. [Relative to calibration_dir]
        save_dir: static/imu
        random_walk_multiplier: 10
        white_noise_multiplier: 5
        # The following settings do NOT change.
        validation:
            min_duration_hours: 3
            max_bias_drift: 0.01

    camera_imu:
        # Where to save results. [Relative to calibration_dir]
        save_dir: dynamic/extrinsincs
        target: default
        reprojection_sigma: 1.0
        # The following settings do NOT change.
        output_formats: [yaml, pdf, txt]
        validation:
            min_images: 100
            max_reprojection_error: 1.5
